// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LXFVideoCacheHostApi {
  /// 转换为缓存代理URL
  func convertToCacheProxyUrl(url: String) throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LXFVideoCacheHostApiSetup {
  /// The codec used by LXFVideoCacheHostApi.
  /// Sets up an instance of `LXFVideoCacheHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LXFVideoCacheHostApi?) {
    /// 转换为缓存代理URL
    let convertToCacheProxyUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.video_cache.LXFVideoCacheHostApi.convertToCacheProxyUrl", binaryMessenger: binaryMessenger)
    if let api = api {
      convertToCacheProxyUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        do {
          let result = try api.convertToCacheProxyUrl(url: urlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      convertToCacheProxyUrlChannel.setMessageHandler(nil)
    }
  }
}
